POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}
###
GET http://localhost:8080/users?id=someStingId
Authorization: 46134297887903


###
GET http://localhost:8080/users?name=Victor
Authorization: 1873954907296942

###
DELETE http://localhost:8080/users?id=72gxdnckgdy
Authorization: 7213208700860898


###
PUT http://localhost:8080/users
Authorization: 1873954907296942
Content-Type: application/json

{
    "name": "Katya",
    "age": 30,
    "email": "lanadelrey@gmail.ua",
    "workingPosition": 1
} 
